'\" t
.\"     Title: fldev
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/14/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "FLDEV" "1" "10/14/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
fldev \- Present partitions from a disk image in a virtual file\-system\&.
.SH "SYNOPSIS"
.sp
\fBfldev\fR [\-o \fIFUSEOPTS\fR] \fIDISKIMAGE\fR \fIMOUNTPOINT\fR
.SH "DESCRIPTION"
.sp
FLDev loads a disk image named \fIDISKIMAGE\fR (with a partition table inside) and presents partitions found in it the same way Linux would do it under its /dev (at least for MSDOS format partition tables)\&. The \fIMOUNTPOINT\fR has to be an empty directory, and the partitions found in the disk image will be "virtual" files in the \fIMOUNTPOINT\fR directory\&.
.sp
For each partition, fldev will assign a number \fIN\fR, and show a file called "\fIhdaN\fR" under \fIMOUNTPOINT\fR\&. This file will be mapped (for reading and writing) to the corresponding part of \fIDISKIMAGE\fR\&.
.sp
For MSDOS format partition tables, primary partitions will be numbered from 1 to 4, and logical partitions from 5 to above\&.
.SH "EXAMPLE"
.PP
Mount the file \fImyimage\fR in a \fIparts\fR directory
.RS 4
fldev myimage parts
.RE
.SH "LIMITATIONS"
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBImportant\fR
.ps -1
.br
.sp
No testing has been made for non\-MSDOS format partition tables\&.
.sp .5v
.RE
.SH "LICENSE"
.sp
Both FLDev and this man page are licensed under the WTFPL\&.
.SH "SEE ALSO"
.sp
parted(1), fusermount(1)
