'\" t
.\"     Title: fldev
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 2016-02-05
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "FLDEV" "1" "2016-02-05" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
fldev \- Mount a disk image to access the contained partitions
.SH "SYNOPSIS"
.sp
\fBfldev\fP [\-o \fIFUSEOPTS\fP] \fIDISKIMAGE\fP \fIMOUNTPOINT\fP
.SH "DESCRIPTION"
.sp
FLDev mounts a disk image file \fIDISKIMAGE\fP at \fIMOUNTPOINT\fP to present the partitions contained in \fIDISKIMAGE\fP.
\fIDISKIMAGE\fP must contain a partition table.
.sp
The partitions are exposed in the same fashion Linux would expose in /dev.
.sp
For each partition, fldev will assign a number \fIX\fP, and show a file called "\fIhdaX\fP" under \fIMOUNTPOINT\fP. For MSDOS format partition tables, primary partitions will be numbered from 1 to 4, and logical partitions will start from 5.
.sp
Any read/write access to the partitions files accessible under \fIMOUNTPOINT\fP will be mapped to the corresponding region in the \fIDISKIMAGE\fP file.
.sp
File permissions of \fIDISKIMAGE\fP are respected but permissions changes after mouting may not be reflected.
File permissions under \fIMOUNTPOINT\fP can be changed with \fIchmod\fP(1) and will be respected.
.SH "OPTIONS"
.sp
FLDev supports all the standard FUSE options:
.sp
\fB\-f\fP
.RS 4
Run in foreground, do not daemonize.
.RE
.sp
\fB\-d\fP
.RS 4
Run in foreground and print debug information.
.RE
.sp
\fB\-s\fP
.RS 4
Run single\-threaded.
.RE
.sp
\fB\-o\fP \fIOPTION1\fP=\fIVALUE1\fP,\fI...\fP
.RS 4
Pass additional options.
.RE
.sp
FUSE supports a number of parameters to \fB\-o\fP, see \fIfuse\fP(8) for a description of them.
.sp
Additionally, FLDev supports these parameters to \fB\-o\fP:
.sp
\fBprefix\fP=\fINAME\fP
.RS 4
Name the exposed partitions with the prefix \fINAME\fP instead of "\fIhda\fP".
.RE
.SH "EXAMPLE"
.sp
Mount the file image.raw\*(Aq in a \fImy_partitions\fP directory
.RS 4
fldev \-o prefix=sdc myimage.raw my_partitions
.RE
.sp
Then, listing the \fImy_partitions\fP dir could give files \fIsdc1\fP, \fIsdc2\fP.
.SH "LICENSE"
.sp
Both FLDev and this man page are licensed under the WTFPL.
.SH "SEE ALSO"
.sp
\fIparted\fP(1), \fIfusermount\fP(1), \fIfuse\fP(8)